### ISSUE TITLE
Does not work on linux

### ISSUE THREAD

**Issue by ghost** [quadion/iOSValidation#1]
This script is great. Thanks.  To get this to work on an ubuntu box, I had to add apple's root certificate to the store before trying to verify it.

apple_cert = OpenSSL::X509::Certificate.new(File.read(File.join('certs', 'AppleIncRootCertificate.cer')))
store.add_cert(apple_cert)

You can get apple's cert here:

http://www.apple.com/certificateauthority/

**Comment by quadion** [comment]
How are you compiling in Linux, by the way? We use this script on a Jenkins instance running on a mac.

**Comment by ghost** [comment]
The actual compilation happens on a mac mini, but I didn't want it to even pick up the compilation job if the certificates/profiles were bad. So the linux box checks that info and only spins up a job if the data is correct.

**Comment by jspooner** [comment]
@cmoscardini You definitely deserve a metal of honor or peace award for this.  I have the same problem!
